=== api-evangelist/apis-guru/json-schema/apis-guru-metrics-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/apis-guru/refs/heads/main/json-schema/apis-guru-metrics-schema.json",
  "title": "Metrics",
  "description": "List of basic metrics",
  "additionalProperties": false,
  "example": {
    "datasets": [],
    "fixedPct": 22,
    "fixes": 81119,
    "invalid": 598,
    "issues": 28,
    "numAPIs": 2501,
    "numDrivers": 10,
    "numEndpoints": 106448,
    "numProviders": 659,
    "numSpecs": 3329,
    "stars": 2429,
    "thisWeek": {
      "added": 45,
      "updated": 171
    },
    "unofficial": 25,
    "unreachable": 123
  },
  "properties": {
    "datasets": {
      "description": "Data used for charting etc",
      "items": {},
      "type": "array"
    },
    "fixedPct": {
      "description": "Percentage of all APIs where auto fixes have been applied",
      "type": "integer"
    },
    "fixes": {
      "description": "Total number of fixes applied across all APIs",
      "type": "integer"
    },
    "invalid": {
      "description": "Number of newly invalid APIs",
      "type": "integer"
    },
    "issues": {
      "description": "Open GitHub issues on our main repo",
      "type": "integer"
    },
    "numAPIs": {
      "description": "Number of unique APIs",
      "minimum": 1,
      "type": "integer"
    },
    "numDrivers": {
      "description": "Number of methods of API retrieval",
      "type": "integer"
    },
    "numEndpoints": {
      "description": "Total number of endpoints inside all definitions",
      "minimum": 1,
      "type": "integer"
    },
    "numProviders": {
      "description": "Number of API providers in directory",
      "type": "integer"
    },
    "numSpecs": {
      "description": "Number of API definitions including different versions of the same API",
      "minimum": 1,
      "type": "integer"
    },
    "stars": {
      "description": "GitHub stars for our main repo",
      "type": "integer"
    },
    "thisWeek": {
      "description": "Summary totals for the last 7 days",
      "properties": {
        "added": {
          "description": "APIs added in the last week",
          "type": "integer"
        },
        "updated": {
          "description": "APIs updated in the last week",
          "type": "integer"
        }
      },
      "type": "object"
    },
    "unofficial": {
      "description": "Number of unofficial APIs",
      "type": "integer"
    },
    "unreachable": {
      "description": "Number of unreachable (4XX,5XX status) APIs",
      "type": "integer"
    }
  },
  "required": [
    "numSpecs",
    "numAPIs",
    "numEndpoints"
  ],
  "type": "object"
}

=== api-evangelist/apis-guru/examples/apis-guru-metrics-example.json
{
  "datasets": [
    "example-value"
  ],
  "fixedPct": 42,
  "fixes": 42,
  "invalid": 42,
  "issues": 42,
  "numAPIs": 42,
  "numDrivers": 42,
  "numEndpoints": 42,
  "numProviders": 42,
  "numSpecs": 42,
  "stars": 42,
  "thisWeek": {
    "added": 42,
    "updated": 42
  },
  "unofficial": 42,
  "unreachable": 42
}
